apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: orion
  name: orion
spec:
  selector:
    matchLabels:
      run: orion
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: orion
    spec:
      containers:
      - image: gcr.io/busviz/orion:latest
        imagePullPolicy: IfNotPresent
        name: orion
        resources:
          requests:
            cpu: 0.03
        env:
         - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: aws_secret_access_key
          - name: ORION_CONFIG_JSON
            value: >
              {
                "s3_bucket": "orion-vehicles",
                "agencies": [
                  {
                    "id": "ttc",
                    "provider": "nextbus",
                    "nextbus_agency_id": "ttc"
                  },
                  {
                    "id": "grt",
                    "provider": "gtfs-realtime",
                    "gtfs_realtime_url": "http://webapps.regionofwaterloo.ca/api/grt-routes/api/vehiclepositions"
                  },
                  {
                    "id": "brampton",
                    "provider": "gtfs-realtime",
                    "gtfs_realtime_url": "https://nextride.brampton.ca:81/API/VehiclePositions?format=gtfs.proto"
                  },
                  {
                    "id": "peterborough",
                    "provider": "gtfs-realtime",
                    "gtfs_realtime_url": "http://pt.mapstrat.com/current/gtfrealtime_VehiclePositions.bin"
                  },
                  {
                    "id": "barrie",
                    "provider": "gtfs-realtime",
                    "gtfs_realtime_url": "http://www.myridebarrie.ca/gtfs/GTFS_VehiclePositions.pb"
                  }
                ]
              }

