apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: orion
  name: orion
spec:
  selector:
    matchLabels:
      run: orion
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: orion
    spec:
      containers:
      - image: gcr.io/busviz/orion:latest
        imagePullPolicy: IfNotPresent
        name: orion
        resources:
          requests:
            cpu: 0.03
        env:
          - name: ORION_CONFIG_JSON
            value: >
              {
                "s3_bucket": "orion-vehicles",
                "agencies": [
                  {
                    "id": "muni",
                    "provider": "nextbus",
                    "nextbus_agency_id": "sf-muni"
                  },
                  {
                    "id": "ttc",
                    "provider": "nextbus",
                    "nextbus_agency_id": "ttc"
                  },
                  {
                    "id": "marin",
                    "provider": "marin"
                  },
                  {
                    "id": "grt",
                    "provider": "gtfs-realtime",
                    "gtfs_realtime_url": "http://192.237.29.212:8080/gtfsrealtime/VehiclePositions"
                  }
                ]
              }

